2017-10-05 20:59:30,299 47.py[line:39] DEBUG Information during calling f():
2017-10-05 20:59:30,299 47.py[line:24] INFO [INFO]: calling method g() in f()
2017-10-05 20:59:30,299 47.py[line:27] INFO [INFO]: calling method h() in g()
2017-10-05 20:59:30,299 47.py[line:30] INFO [INFO]: Delete element in gList h()
2017-10-05 20:59:30,300 47.py[line:32] INFO [INFO]: calling method i() in h()
2017-10-05 20:59:30,300 47.py[line:35] INFO [INFO]: calling method i() 
2017-10-05 20:59:30,300 47.py[line:47] ERROR [ERROR]: Sorry, Exception occured, you accessed an element out of range.
2017-10-05 20:59:30,300 47.py[line:48] CRITICAL object info:list index out of range
2017-10-05 20:59:30,300 47.py[line:49] CRITICAL Error Type:<type 'exceptions.IndexError'>, Error Information:list index out of range
2017-10-05 20:59:30,300 47.py[line:51] CRITICAL   File "47.py", line 41, in <module>
    f()
  File "47.py", line 25, in f
    return g()
  File "47.py", line 28, in g
    return h()
  File "47.py", line 33, in h
    return i()
  File "47.py", line 37, in i
    print gList[7]

